### ISSUE TITLE
Cannot use goto command to/from the Greenwilds

### ISSUE THREAD

**Issue by zacklucky7** [IRE-Mudlet-Mapping/StarmournCrowdmap#12]
I can't seem to use the _goto_ command to and from the Greenwilds. Trying to go to the Greenwilds gives me the message (via _goto greenwilds_):

_(mapper): Checked 0 exits in that area, and none of them worked :( I Don't know how to get you 
there._

Trying to use _goto_ from inside the Greenwilds, eg. _goto omni 1_

_(mapper): Checked 1 exits in that area, and none of them worked :( I Don't know how to get you 
there._

The Greenwilds is accessible from a PTP in Sabiak at room 1566. Greenwilds is option 1. That is the only destination listed.
The other end of the PTP inside the Greenwilds is room 4283. Sabiak is option 1. That is the only destination listed.

The _goto_ command from Sabiak works as expected.

Mapper version: 19.1.1
Mudlet version: 3.16.1

**Comment by vadi2** [comment]
And just to check - you don't have greenwilds locked? https://wiki.mudlet.org/w/IRE_mapping_script#arealock

**Comment by Hevlikn** [comment]
No, there were missing special exits; will be pushing soon

**Comment by zacklucky7** [comment]
This is resolved now
