### ISSUE TITLE
Unable to use goto command -- 0 exits found if special exits are involved

### ISSUE THREAD

**Issue by zacklucky7** [IRE-Mudlet-Mapping/StarmournCrowdmap#16]
This issue seems to have appeared at some point between 11:42 PM EST 1/30/2019 and 12:31 PM EST 1/31/2019.

I am unable to use the _goto_ command to go to areas that involve using a special exit like a PTP. When I try, I get this message:

_(mapper): Checked 0 exits in that area, and none of them worked :( I Don't know how to get you 
there._

Using _goto_ between two areas that have walking exits between them work as expected.

The only difference that I knowingly made was to manually download the latest map provided by the MUD through Mudlet settings, since a new area (Wundishu Biotech) was added.

I thought this was something wrong with my installation, but someone else confirmed they were having the issue. Here is what I tried to troubleshoot:

1. Disabled crowdmap. **no change**
2. Disabled dashing (because of my recent issue with trying to sprint over special exits). **no change**
3. Enabled and disabled _lockspecials_. **no change**
4. Uninstalled and reinstalled _mudlet-mapper_, then rebooted Mudlet. **no change**
5. Loaded a previously working Mudlet profile, from before the issue began. **no change**
6. Uninstalled and reinstalled Mudlet. **no change**

mmp.version: 19.1.2
Mudlet version: 3.16.1

**Comment by zacklucky7** [comment]
One thing that we have in common is that we both visited the new area, Wundishu Biotech

**Comment by keneanung** [comment]
If you downloaded the map through the Mudlet settings, it's very likely that you now use the official map, which doesn't have any special exits as far as I know.

**Comment by zacklucky7** [comment]
Is there a way to undo that action, like force a crowdmap update?

**Comment by keneanung** [comment]
Yes, at the bottom of `rl` is a link to force a map update.

**Comment by zacklucky7** [comment]
That fixed it! Thank you very much.

**Comment by Hevlikn** [comment]
The new area hasn't been mapped yet, so that's why you can't speedwalk to/from it. Will update it now
